WebApplication2/Areas/admin/Controllers/RathoreDetailsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using RS.DataModel;
using RS.BusinessLogicLayer;

namespace WebApplication2.Areas.admin.Controllers
{
   
    public class RathoreDetailsController : BaseController
    {
        // GET: admin/RathoreDetail

        [RathoreSamajAuth(Order= 1, Roles = "1,2,99",Users = null)]
        public ActionResult Index()
        {
            RathoreDetailBL _rathoreDetailBL = new RathoreDetailBL();
            List<RathoreDetailModel> lstRathoreDetails = _rathoreDetailBL.GetAllRathoreDetail();
            return View(lstRathoreDetails);
        }


        [RathoreSamajAuth(Order = 1, Roles = "1,2,99", Users = null)]
        public ActionResult AddRathoreDetail()
        {
            @ViewBag.Style = "alert alert-success";
            RathoreDetailModel rathoreDetails = new RathoreDetailModel();
            BindDropdown(ref rathoreDetails);
            return View(rathoreDetails);
        }

        [HttpPost]
        [RathoreSamajAuth(Order = 1, Roles = "1,2,99", Users = null)]
        public ActionResult AddRathoreDetail(RathoreDetailModel obj)
        {
            @ViewBag.Style = "alert alert-success";
            if (ModelState.IsValid)
            {
                RathoreDetailBL _contactDetailBL = new RathoreDetailBL();

                obj.DateOfBirth = Convert.ToDateTime(obj.DateOfBirthFormated);
                obj.CreatedBy = LoginUserID;
                if (!_contactDetailBL.CheckRathoreDetailExist(obj.Name, obj.DateOfBirth))
                {
                    int result = _contactDetailBL.InsertRathoreDetail(obj);
                   // BindDropdown(ref obj);
                    ViewBag.Saved = true;

                    if (result == 1)
                    {
                        ViewBag.Style = "alert alert-success";
                        ViewBag.Message = "जानकारी डेटाबेस मे दर्ज हो गया है | धन्यवाद् ";
                        ModelState.Clear();
                    }
                    else
                    {
                        ViewBag.Style = "alert alert-danger";
                        ViewBag.Message = "तकनिकी खराबी की वजह से आपका सन्देश नहीं मिला , कृपया दुबारा भेजे.  ";
                    }
                }
                else
                {
                    ViewBag.Saved = true;
                    ViewBag.Style = "alert alert-danger";
                    ViewBag.Message = " इस नाम की जानकारी पहले से अंकित है. ";
                }

            }
            BindDropdown(ref obj);
            return View(obj);
        }

        [RathoreSamajAuth(Order = 1, Roles = "1,2,99", Users = null)]
        public ActionResult EditRathoreDetail(int id)
        {
            TempData.Remove("Name");
            TempData.Remove("DateofBirth");

            ViewBag.Style = "alert alert-success";
            RathoreDetailBL _rathoreDetailBL = new RathoreDetailBL();
            RathoreDetailModel lstRathoreDetails = new RathoreDetailModel();
            lstRathoreDetails = _rathoreDetailBL.GetRathoreDetailId(id);

            TempData["Name"] = lstRathoreDetails.Name;
            TempData["DateofBirth"] = lstRathoreDetails.DateOfBirth;

            BindDropdown(ref lstRathoreDetails);
            string datetime = string.Format("{0:yyyy-MM-dd}", lstRathoreDetails.DateOfBirth);
            lstRathoreDetails.DateOfBirthFormated = datetime;
            return View(lstRathoreDetails);
        }

        [HttpPost]
        [RathoreSamajAuth(Order = 1, Roles = "1,2,99", Users = null)]
        public ActionResult EditRathoreDetail(RathoreDetailModel obj)
        {
            @ViewBag.Style = "alert alert-success";
            if (ModelState.IsValid)
            {
                RathoreDetailBL _contactDetailBL = new RathoreDetailBL();
                obj.DateOfBirth = Convert.ToDateTime(obj.DateOfBirthFormated);
                string Name = Convert.ToString(TempData["Name"]).Trim();
                DateTime DateofBirth = Convert.ToDateTime(TempData["DateofBirth"]);

                TempData.Keep("Name");
                TempData.Keep("DateofBirth");


                if (Name != obj.Name.Trim()  || (!obj.DateOfBirth.Equals(DateofBirth)))
                {

                    if (_contactDetailBL.CheckRathoreDetailExist(obj.Name, obj.DateOfBirth))
                    {
                        ViewBag.Saved = true;
                        ViewBag.Style = "alert alert-danger";
                        ViewBag.Message = " इस नाम की जानकारी पहले से अंकित है. ";
                        BindDropdown(ref obj);
                        return View(obj);
                    }
                }

                obj.ModifiedBy = LoginUserID;

                int result = _contactDetailBL.UpdateRathoreDetail(obj);
                   
                    ViewBag.Saved = true;

                    if (result == 1)
                    {
                        ViewBag.Style = "alert alert-success";
                        ViewBag.Message = "जानकारी डेटाबेस मे दर्ज हो गया है | धन्यवाद् ";
                    }
                    else
                    {
                        ViewBag.Style = "alert alert-danger";
                        ViewBag.Message = "तकनिकी खराबी की वजह से आपका सन्देश नहीं मिला , कृपया दुबारा भेजे.  ";
                    }
               

                BindDropdown(ref obj);

            }
            return View(obj);
        }

        [RathoreSamajAuth(Order = 1, Roles = "1,99", Users = null)]
        public ActionResult DeleteRathoreDetail(int id)
        {
            RathoreDetailBL _contactDetailBL = new RathoreDetailBL();

            int result = _contactDetailBL.DeleteRathoreDetail(id);
            if (result == 1)
            {
                TempData["Message"] = "चयन किया रिकॉर्ड मिटा दिया गया है !! ";
            }
            else
            {
                TempData["Message"] = "तकनिकी खराबी की वजह से आपका सन्देश नहीं मिला , कृपया दुबारा भेजे.  ";
            }

            return RedirectToAction("Index");
        }


        [HttpPost]
        public JsonResult CountryAutosuggest(string Prefix)
        {
            AutoSuggestTextBL obj = new AutoSuggestTextBL();

            var countryList = (from N in obj.GetAllCountry()
                               where N.Value.ToUpper().StartsWith(Prefix.ToUpper())
                               select new { N.Value });
            return Json(countryList, JsonRequestBehavior.AllowGet);

        }


        [HttpPost]
        public JsonResult StateAutosuggest(string Prefix)
        {
            AutoSuggestTextBL obj = new AutoSuggestTextBL();

            var stateList = (from N in obj.GetAllStates()
                             where N.Value.ToUpper().StartsWith(Prefix.ToUpper())
                             select new { N.Value });
            return Json(stateList, JsonRequestBehavior.AllowGet);

        }

        [HttpPost]
        public JsonResult DistrictAutosuggest(string Prefix)
        {
            AutoSuggestTextBL obj = new AutoSuggestTextBL();

            var distList = (from N in obj.GetAllDistrict()
                            where N.Value.ToUpper().StartsWith(Prefix.ToUpper())
                            select new { N.Value });
            return Json(distList, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult LocationAutosuggest(string Prefix)
        {
            AutoSuggestTextBL obj = new AutoSuggestTextBL();

            var distlocation = (from N in obj.GetAllLocation()
                                where N.Value.ToUpper().StartsWith(Prefix.ToUpper())
                                select new { N.Value });
            return Json(distlocation, JsonRequestBehavior.AllowGet);
        }



        private void BindDropdown(ref RathoreDetailModel rathoreDetails)
        {
            rathoreDetails.GenderDropDown = GetGenderDetail();
        }

        private IEnumerable<DropdownList> GetGenderDetail()
        {
            return new List<DropdownList>
            {
                new DropdownList(){Value = "Female", Key="F" },
                new DropdownList(){Value = "Male", Key="M" }
            };
        }

    }
}

WebApplication2/Controllers/RathoreDetailController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using RS.DataModel;
using RS.BusinessLogicLayer;

namespace WebApplication2.Controllers
{
    public class RathoreDetailController : Controller
    {
        // GET: RathoreDetail
        public ActionResult Index()
        {
            RathoreDetailBL _rathoreDetailBL = new RathoreDetailBL();
            RathoreDetailDisplayModel objDisplay =  _rathoreDetailBL.GetDetailsToDisplay();

          
            List<RathoreDetailModel> rathoreDetail = new List<RathoreDetailModel>();
            foreach(var val in _rathoreDetailBL.GetAllRathoreDetail())
            {
                val.Age = CalculateAge(Convert.ToDateTime(val.DateOfBirth));
                rathoreDetail.Add(val);
            }



            objDisplay.RathoreDetails = rathoreDetail.OrderBy(o => o.Name).ToList();

            return View(objDisplay);
        }

        public ActionResult GetChartView(int id)
        {
            TempData["rathoreDetailId"] = id;
            return View();
        }


        [HttpGet]
        public JsonResult GetHierarchicalDetail()
        {
            int rathoreDetailId = 0;
            RathoreDetailBL _rathoreDetailBL = new RathoreDetailBL();

            if (TempData["rathoreDetailId"] != null)
                rathoreDetailId = Convert.ToInt32(TempData["rathoreDetailId"]);

            List<HRathoreDetails> empChartList = new List<HRathoreDetails>();
            empChartList = _rathoreDetailBL.GetHierarchicalDetail(rathoreDetailId);

            return Json(empChartList, JsonRequestBehavior.AllowGet);
        }

        /// <summary>  
        /// For calculating only age  
        /// </summary>  
        private static int CalculateAge(DateTime dateOfBirth)
        {
            int age = 0;
            age = DateTime.Now.Year - dateOfBirth.Year;
            if (DateTime.Now.DayOfYear < dateOfBirth.DayOfYear)
                age = age - 1;

            return age;
        }
    }
}

WebApplication2/Areas/admin/Views/RathoreDetails/Index.cshtml
@model IEnumerable<RS.DataModel.RathoreDetailModel>
@using GridMvc.Html
@using RS.DataModel;

@{
    ViewBag.Title = "..: Admin : Rathore Details :..";
    Layout = "~/Areas/admin/Views/Shared/_Layout.cshtml";
}

<h1 style="color:#146eb0;text-align:left">राठौर जानकारी </h1>
<hr />
<ol class="breadcrumb">
    <li><a href="#">प्रारम्भ</a></li>
    <li class="active">राठौर जानकारी</li>
</ol>

<p style="text-align:left">
    <b> क्षत्रिय राठौर समाज के एडमिन पोर्टल मे आप का बहुत बहुत स्वागत है.</b> <br /><br />
</p>

<div class="col-lg-12 col-sm-12 col-md-12 text-right">
    @Html.ActionLink("नया जानकारी", "AddRathoreDetail", "RathoreDetail", new { @class = "btn btn-primary" })
    @*<button type="button" class="btn btn-danger"></button>*@
</div>


    <div class="row">
        <div class="col-md-12">
            @if (TempData["Message"] != null)
            {
                <div class="alert alert-success" role="alert">@TempData["Message"]</div>
            }
        </div>
    </div>

<br />

    <div class="row">
        <div class="col-md-12">
            @Html.Grid(Model).Columns(columns =>
       {
           columns.Add()
                 .Titled("")
                 .SetWidth(10)
                 .Filterable(true)
                 .Sanitized(false)
                 .Encoded(false)
                 .RenderValueAs(c => Html.ActionLink(" ", "EditRathoreDetail", "RathoreDetails", new { id = c.RathoreDetailId }, new { @class = "glyphicon glyphicon-edit" })
                 .ToHtmlString());

           if (Session["LoginSuccesFull"] != null && (((LoginModel)Session["LoginSuccesFull"]).Role == 99 || ((LoginModel)Session["LoginSuccesFull"]).Role == 1))
           {
               columns.Add()
                   .Titled("")
                   .SetWidth(10)
                   .Filterable(true)
                   .Sanitized(false)
                   .Encoded(false)
                   .RenderValueAs(c => Html.ActionLink(" ", "DeleteRathoreDetail", "RathoreDetails", new { id = c.RathoreDetailId }, new { onclick = "return confirm('Are you sure you wish to delete this Rathore details?');", @class = "glyphicon glyphicon-trash" })
                   .ToHtmlString());
           }
           columns.Add(c => c.Name).Titled("पूरा नाम").Filterable(true).Sortable(true);
           columns.Add(c => c.FatherName).Titled("पिता का नाम").Filterable(true);
           columns.Add(c => c.DateOfBirth).Titled("जन्म तारीख").Filterable(true).Sortable(true)
                   .RenderValueAs(c => Convert.ToDateTime(c.DateOfBirth).ToString("d"));
           columns.Add(c => c.PhoneNumber).Titled("फ़ोन नंबर").Filterable(true);
           columns.Add(c => c.CurrentDistrictName).Titled("वर्तमान जिला").Filterable(true);
           columns.Add(c => c.CurrentLocationName).Titled("वर्तमान स्थान").Filterable(true);
           columns.Add(c => c.NativeDistrictName).Titled("स्थायी जिला").Filterable(true);
           columns.Add(c => c.NativeLocationName).Titled("स्थायी स्थान").Filterable(true);

       }).WithPaging(10).Sortable(true)


        </div>

    </div>