WebApplication2/Areas/admin/Controllers/EventsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using RS.DataModel;
using RS.BusinessLogicLayer;

namespace WebApplication2.Areas.admin.Controllers
{
    [RathoreSamajAuth]
    public class EventsController : BaseController
    {
        EventBL _eventDetailBL;
        public EventsController()
        {
            _eventDetailBL = new EventBL();
        }
        // GET: admin/Events
        [RathoreSamajAuth(Order = 1, Roles = "1,2,99", Users = null)]
        public ActionResult Index()
        {
            List<EventModel> lstEventDetails = _eventDetailBL.GetAllEvent();
            return View(lstEventDetails);
        }

        [RathoreSamajAuth(Order = 1, Roles = "1,2,99", Users = null)]
        public ActionResult AddEvent()
        {
            @ViewBag.Style = "alert alert-success";
            //RathoreDetailModel rathoreDetails = new RathoreDetailModel();
            // BindDropdown(ref rathoreDetails);
            return View();
        }


        [HttpPost]
        [RathoreSamajAuth(Order = 1, Roles = "1,2,99", Users = null)]
        public ActionResult AddEvent(EventModel obj)
        {
            @ViewBag.Style = "alert alert-success";
            if (ModelState.IsValid)
            {

                obj.CreatedBy = LoginUserID;
                obj.EventDateFrom = Convert.ToDateTime(obj.EventDateFromFormated);
                obj.EventDateTo = Convert.ToDateTime(obj.EventDateToFormated);

                int result = _eventDetailBL.InsertEvent(obj);
                // BindDropdown(ref obj);
                ViewBag.Saved = true;

                if (result == 1)
                {
                    ViewBag.Style = "alert alert-success";
                    ViewBag.Message = "जानकारी डेटाबेस मे दर्ज हो गया है | धन्यवाद् ";
                    ModelState.Clear();
                }
                else
                {
                    ViewBag.Style = "alert alert-danger";
                    ViewBag.Message = "तकनिकी खराबी की वजह से आपका सन्देश नहीं मिला , कृपया दुबारा भेजे.  ";
                }
            }
            return View(obj);
        }


        [RathoreSamajAuth(Order = 1, Roles = "1,2,99", Users = null)]
        public ActionResult EditEvent(int id)
        {
            ViewBag.Style = "alert alert-success";
            EventModel eventModel = new EventModel();
            eventModel = _eventDetailBL.GetEventId(id);


            string datetimeFrom = string.Format("{0:yyyy-MM-dd}", eventModel.EventDateFrom);
            string datetimeTo = string.Format("{0:yyyy-MM-dd}", eventModel.EventDateTo);

            eventModel.EventDateFromFormated = datetimeFrom;
            eventModel.EventDateToFormated = datetimeTo;

            return View(eventModel);
        }


        [HttpPost]
        [RathoreSamajAuth(Order = 1, Roles = "1,2,99", Users = null)]
        public ActionResult EditEvent(EventModel obj)
        {
            @ViewBag.Style = "alert alert-success";
            if (ModelState.IsValid)
            {
                obj.ModifiedBy = LoginUserID;
                obj.EventDateFrom = Convert.ToDateTime(obj.EventDateFromFormated);
                obj.EventDateTo = Convert.ToDateTime(obj.EventDateToFormated);

                //string Name = Convert.ToString(TempData["Name"]).Trim();
                //DateTime DateofBirth = Convert.ToDateTime(TempData["DateofBirth"]);

                //TempData.Keep("Name");
                //TempData.Keep("DateofBirth");


                int result = _eventDetailBL.UpdateEvent(obj);

                ViewBag.Saved = true;

                if (result == 1)
                {
                    ViewBag.Style = "alert alert-success";
                    ViewBag.Message = "जानकारी डेटाबेस मे दर्ज हो गया है | धन्यवाद् ";
                }
                else
                {
                    ViewBag.Style = "alert alert-danger";
                    ViewBag.Message = "तकनिकी खराबी की वजह से आपका सन्देश नहीं मिला , कृपया दुबारा भेजे.  ";
                }

            }
            return View(obj);
        }


        [RathoreSamajAuth(Order = 1, Roles = "1,99", Users = null)]
        public ActionResult DeleteEvent(int id)
        {
            int result = _eventDetailBL.DeleteEvent(id);
            if (result == 1)
            {
                TempData["Message"] = "चयन किया रिकॉर्ड मिटा दिया गया है !! ";
            }
            else
            {
                TempData["Message"] = "तकनिकी खराबी की वजह से आपका सन्देश नहीं मिला , कृपया दुबारा भेजे.  ";
            }

            return RedirectToAction("Index");
        }


        [HttpPost]
        public JsonResult DistrictAutosuggest(string Prefix)
        {
            AutoSuggestTextBL obj = new AutoSuggestTextBL();

            var distList = (from N in obj.GetAllDistrict()
                            where N.Value.ToUpper().StartsWith(Prefix.ToUpper())
                            select new { N.Value });
            return Json(distList, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult LocationAutosuggest(string Prefix)
        {
            AutoSuggestTextBL obj = new AutoSuggestTextBL();

            var distlocation = (from N in obj.GetAllLocation()
                                where N.Value.ToUpper().StartsWith(Prefix.ToUpper())
                                select new { N.Value });
            return Json(distlocation, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult EventAutosuggest(string Prefix)
        {
            AutoSuggestTextBL obj = new AutoSuggestTextBL();

            var eventsType = (from N in obj.GetEventType()
                                where N.Value.ToUpper().StartsWith(Prefix.ToUpper())
                                select new { N.Value });
            return Json(eventsType, JsonRequestBehavior.AllowGet);
        }
    }
}

WebApplication2/Controllers/EventController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using RS.DataModel;
using RS.BusinessLogicLayer;

namespace WebApplication2.Controllers
{
    public class EventController : Controller
    {

        EventBL _eventDetailBL;
        public EventController()
        {
            _eventDetailBL = new EventBL();
        }
        // GET: Event
        public ActionResult Index()
        {
            EventModelDetails lstEventDetails = new EventModelDetails();

            var allEvents = _eventDetailBL.GetAllEvent();

            lstEventDetails.CurrentMonthEvent = allEvents.Where(o => o.EventDateFrom.Value.Month == DateTime.Now.Month).ToList();
            lstEventDetails.TotalEvent = allEvents;
            return View(lstEventDetails);
        }

        public ActionResult EventDetails(int id)
        {
            ViewBag.Style = "alert alert-success";
            EventModelView eventModelView = new EventModelView();
            eventModelView.SelectedEvent = _eventDetailBL.GetEventId(id);
            eventModelView.CurrentMonthEvent = _eventDetailBL.GetAllEvent().Where(o => o.EventDateFrom.Value.Month == DateTime.Now.Month).ToList();

            return View(eventModelView);
        }
    }
}

WebApplication2/Areas/admin/Views/Events/AddEvent.cshtml
@model RS.DataModel.EventModel
@using RS.DataModel;

@{
    ViewBag.Title = "AddEvent";
    Layout = "~/Areas/admin/Views/Shared/_Layout.cshtml";

}

<h1 style="color:#146eb0;text-align:left">नया कार्यक्रम</h1>
<hr />
<ol class="breadcrumb">
    <li><a href="#">प्रारम्भ</a></li>
    <li><a href="#">कार्यक्रम</a></li>
    <li class="active">नया कार्यक्रम </li>
</ol>



@using (Html.BeginForm("AddEvent", "Events", FormMethod.Post, new { role = "form", @novalidate = "novalidate" }))
{
    <div class="row text-right" style="padding-right:10px">
        @Html.ActionLink("पीछे जाये", "Index", "Events", new { @class = "btn btn-default" }) &nbsp;
        <button type="submit" class="btn btn-primary">जमा करें</button>
    </div>
    <br />

    <div class="row" style="margin: 4px">

        @if (ViewBag.Saved == true)
        {
            <div class="@ViewBag.Style" role="alert">@ViewBag.Message</div>
        }


        <div class="alert alert-warning" role="alert">
            <span class="text-required">*</span> की हुई जानकारी प्रदान करना अनिवार्य है | <br />
            <b style="font-size:16px;color:red">** जानकारी किसी भी भाषा में दर्ज कर सकते हैं  **</b>
        </div>
    </div>


    <div class="panel panel-info">
        <div class="panel-heading">
            जरूरी जानकारी
        </div>
        <div class="panel-body">
            <div class="row">
                <div class="col-sm-12 col-sm-4 col-lg-4">
                    <div class="form-group">
                        <label for="EventTypeName">कार्यक्रम प्रकार</label> <span class="text-required">*</span>
                        @Html.TextBoxFor(model => model.EventTypeName, new { @class = "form-control", placeholder = "Event Type", @maxlength = 100 })
                        @Html.ValidationMessageFor(model => model.EventTypeName, "", new { @class = "text-error" })
                    </div>
                </div>
                <div class="col-sm-12 col-sm-4 col-lg-4">
                    <div class="form-group">
                        <label for="Subject">विषय </label> <span class="text-required">*</span>
                        @Html.TextBoxFor(model => model.Subject, new { @class = "form-control", placeholder = "Subject", @maxlength = 200 })
                        @Html.ValidationMessageFor(model => model.Subject, "", new { @class = "text-error" })
                    </div>
                </div>
                <div class="col-sm-12 col-sm-4 col-lg-4">
                    <div class="form-group">
                      
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="panel panel-info">
        <div class="panel-heading">
            स्थान की  जानकारी
        </div>
        <div class="panel-body">
            <div class="row">
                <div class="col-sm-12 col-sm-4 col-lg-4">
                    <div class="form-group">
                        <label for="DistrictName">जिला </label> <span class="text-required">*</span>
                        @Html.TextBoxFor(model => model.DistrictName, new { @class = "form-control", placeholder = "District Name", @maxlength = 200 })
                        @Html.ValidationMessageFor(model => model.DistrictName, "", new { @class = "text-error" })
                    </div>
                </div>
                <div class="col-sm-12 col-sm-4 col-lg-4">
                    <div class="form-group">
                        <label for="LocationName">स्थान</label> <span class="text-required">*</span>
                        @Html.TextBoxFor(model => model.LocationName, new { @class = "form-control", placeholder = "Location Namee", @maxlength = 100 })
                        @Html.ValidationMessageFor(model => model.LocationName, "", new { @class = "text-error" })
                    </div>
                </div>
                <div class="col-sm-12 col-sm-4 col-lg-4">
                    <div class="form-group">

                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="panel panel-info">
        <div class="panel-heading">
            समय की जानकारी
        </div>
        <div class="panel-body">
            <div class="row">
                <div class="col-sm-12 col-sm-4 col-lg-4">
                    <div class="form-group">
                        <label for="EventDateFrom">दिनांक से</label> <span class="text-required">*</span>
                        @Html.TextBoxFor(model => model.EventDateFromFormated, new { @class = "form-control", placeholder = "Event Date From ", @maxlength = 10,@type = "date" })
                        @Html.ValidationMessageFor(model => model.EventDateFromFormated, "", new { @class = "text-error" })
                    </div>
                </div>
                <div class="col-sm-12 col-sm-4 col-lg-4">
                    <div class="form-group">
                        <label for="EventDateTo">दिनांक तक </label> <span class="text-required">*</span>
                        @Html.TextBoxFor(model => model.EventDateToFormated, new { @class = "form-control", placeholder = "Event Date To", @maxlength = 10, @type = "date" })
                        @Html.ValidationMessageFor(model => model.EventDateToFormated, "", new { @class = "text-error" })
                    </div>
                </div>
                <div class="col-sm-12 col-sm-4 col-lg-4">
                    <div class="form-group">

                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-12 col-lg-4">
                    <div class="form-group">
                        <label for="EventTimeFrom">समय से</label> <span class="text-required">*</span>
                        @Html.TextBoxFor(model => model.EventTimeFrom, new { @class = "form-control", placeholder = "Event Time From ", @maxlength = 100, @type = "time" })
                        @Html.ValidationMessageFor(model => model.EventTimeFrom, "", new { @class = "text-error" })
                    </div>
                </div>
                <div class="col-sm-12 col-lg-4">
                    <div class="form-group">
                        <label for="EventTimeTo">समय तक </label> <span class="text-required">*</span>
                        @Html.TextBoxFor(model => model.EventTimeTo, new { @class = "form-control", placeholder = "Event Time To", @maxlength = 200, @type = "time" })
                        @Html.ValidationMessageFor(model => model.EventTimeTo, "", new { @class = "text-error" })
                    </div>
                </div>
                <div class="col-sm-12  col-lg-4">
                    <div class="form-group">

                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="panel panel-info">
        <div class="panel-heading">
            पूर्ण जानकारी
        </div>
        <div class="panel-body">
            <div class="row">
                <div class="col-sm-12 col-lg-12">
                    <div class="form-group">
                        <label for="Body">विस्तृत जानकारी </label> <span class="text-required">*</span>
                        @Html.TextAreaFor(model => model.Body, new { @class = "form-control col-sm-12", placeholder = "Event Type" })
    @Html.ValidationMessageFor(model => model.Body, "", new { @class = "text-error" })
                    </div>
                </div>
            </div>
        </div>
    </div>
}


<link href="~/Content/jquery-ui.css" rel="stylesheet" />
<script src="~/Scripts/jquery-ui.js"></script>
<script src="//tinymce.cachefly.net/4.0/tinymce.min.js"></script>
<script src="~/Scripts/application/admin/AddEventDetails.js"></script>
<script type="text/javascript">

    var winWidth = "";
    $(document).ready(function () {
        winWidth = $(document).width - 100 + "px";

        tinymce.init({ selector: 'textarea', width: winWidth });
    });

  
</script>

WebApplication2/Areas/admin/Views/Events/EditEvent.cshtml
@model RS.DataModel.EventModel
@using RS.DataModel;

@{
    ViewBag.Title = "AddEvent";
    Layout = "~/Areas/admin/Views/Shared/_Layout.cshtml";

}

<h1 style="color:#146eb0;text-align:left">कार्यक्रम सुधार करे</h1>
<hr />
<ol class="breadcrumb">
    <li><a href="#">प्रारम्भ</a></li>
    <li><a href="#">कार्यक्रम</a></li>
    <li class="active"> कार्यक्रम सुधार</li>
</ol>



@using (Html.BeginForm("EditEvent", "Events", FormMethod.Post, new { role = "form", @novalidate = "novalidate" }))
{
    <div class="row text-right" style="padding-right:10px">
        @Html.ActionLink("पीछे जाये", "Index", "Events", new { @class = "btn btn-default" }) &nbsp;
        <button type="submit" class="btn btn-primary">जमा करें</button>
    </div>
    <br />

    <div class="row" style="margin: 4px">

        @if (ViewBag.Saved == true)
        {
            <div class="@ViewBag.Style" role="alert">@ViewBag.Message</div>
        }


        <div class="alert alert-warning" role="alert">
            <span class="text-required">*</span> की हुई जानकारी प्रदान करना अनिवार्य है | <br />
            <b style="font-size:16px;color:red">** जानकारी किसी भी भाषा में दर्ज कर सकते हैं  **</b>
        </div>
    </div>


    <div class="panel panel-info">
        <div class="panel-heading">
            जरूरी जानकारी
        </div>
        <div class="panel-body">
            <div class="row">
                <div class="col-sm-12 col-sm-4 col-lg-4">
                    <div class="form-group">
                        <label for="EventTypeName">कार्यक्रम प्रकार</label> <span class="text-required">*</span>
                        @Html.TextBoxFor(model => model.EventTypeName, new { @class = "form-control", placeholder = "Event Type", @maxlength = 100 })
                        @Html.HiddenFor(model => model.EventId)
                        @Html.ValidationMessageFor(model => model.EventTypeName, "", new { @class = "text-error" })
                    </div>
                </div>
                <div class="col-sm-12 col-sm-4 col-lg-4">
                    <div class="form-group">
                        <label for="Subject">विषय </label> <span class="text-required">*</span>
                        @Html.TextBoxFor(model => model.Subject, new { @class = "form-control", placeholder = "Subject", @maxlength = 200 })
                        @Html.ValidationMessageFor(model => model.Subject, "", new { @class = "text-error" })
                    </div>
                </div>
                <div class="col-sm-12 col-sm-4 col-lg-4">
                    <div class="form-group">

                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="panel panel-info">
        <div class="panel-heading">
            स्थान की  जानकारी
        </div>
        <div class="panel-body">
            <div class="row">
                <div class="col-sm-12 col-sm-4 col-lg-4">
                    <div class="form-group">
                        <label for="DistrictName">जिला </label> <span class="text-required">*</span>
                        @Html.TextBoxFor(model => model.DistrictName, new { @class = "form-control", placeholder = "District Name", @maxlength = 200 })
                        @Html.ValidationMessageFor(model => model.DistrictName, "", new { @class = "text-error" })
                    </div>
                </div>
                <div class="col-sm-12 col-sm-4 col-lg-4">
                    <div class="form-group">
                        <label for="LocationName">स्थान</label> <span class="text-required">*</span>
                        @Html.TextBoxFor(model => model.LocationName, new { @class = "form-control", placeholder = "Location Name", @maxlength = 100 })
                        @Html.ValidationMessageFor(model => model.LocationName, "", new { @class = "text-error" })
                    </div>
                </div>
                <div class="col-sm-12 col-sm-4 col-lg-4">
                    <div class="form-group">

                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="panel panel-info">
        <div class="panel-heading">
            समय की जानकारी
        </div>
        <div class="panel-body">
            <div class="row">
                <div class="col-sm-12 col-sm-4 col-lg-4">
                    <div class="form-group">
                        <label for="EventDateFrom">दिनांक से</label> <span class="text-required">*</span>
                        @Html.TextBoxFor(model => model.EventDateFromFormated, new { @class = "form-control", placeholder = "Event Date From ", @maxlength = 10, @type = "date" })
                        @Html.ValidationMessageFor(model => model.EventDateFromFormated, "", new { @class = "text-error" })
                    </div>
                </div>
                <div class="col-sm-12 col-sm-4 col-lg-4">
                    <div class="form-group">
                        <label for="EventDateTo">दिनांक तक </label> <span class="text-required">*</span>
                        @Html.TextBoxFor(model => model.EventDateToFormated, new { @class = "form-control", placeholder = "Event Date To", @maxlength = 10, @type = "date" })
                        @Html.ValidationMessageFor(model => model.EventDateToFormated, "", new { @class = "text-error" })
                    </div>
                </div>
                <div class="col-sm-12 col-sm-4 col-lg-4">
                    <div class="form-group">

                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-12 col-lg-4">
                    <div class="form-group">
                        <label for="EventTimeFrom">समय से</label> <span class="text-required">*</span>
                        @Html.TextBoxFor(model => model.EventTimeFrom, new { @class = "form-control", placeholder = "Event Time From ", @maxlength = 100, @type = "time" })
                        @Html.ValidationMessageFor(model => model.EventTimeFrom, "", new { @class = "text-error" })
                    </div>
                </div>
                <div class="col-sm-12 col-lg-4">
                    <div class="form-group">
                        <label for="EventTimeTo">समय तक </label> <span class="text-required">*</span>
                        @Html.TextBoxFor(model => model.EventTimeTo, new { @class = "form-control", placeholder = "Event Time To", @maxlength = 200, @type = "time" })
                        @Html.ValidationMessageFor(model => model.EventTimeTo, "", new { @class = "text-error" })
                    </div>
                </div>
                <div class="col-sm-12  col-lg-4">
                    <div class="form-group">

                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="panel panel-info">
        <div class="panel-heading">
            पूर्ण जानकारी
        </div>
        <div class="panel-body">
            <div class="row">
                <div class="col-sm-12 col-lg-12">
                    <div class="form-group">
                        <label for="Body">विस्तृत जानकारी </label> <span class="text-required">*</span>
                        @Html.TextAreaFor(model => model.Body, new { @class = "form-control col-sm-12", placeholder = "Event Type" })
                        @Html.ValidationMessageFor(model => model.Body, "", new { @class = "text-error" })
                    </div>
                </div>
            </div>
        </div>
    </div>
}


<link href="~/Content/jquery-ui.css" rel="stylesheet" />
<script src="~/Scripts/jquery-ui.js"></script>
<script src="//tinymce.cachefly.net/4.0/tinymce.min.js"></script>
<script src="~/Scripts/application/admin/EditEventDetails.js"></script>

<script type="text/javascript">

    var winWidth = "";
    $(document).ready(function () {
        winWidth = $(document).width - 100 + "px";

        tinymce.init({ selector: 'textarea', width: winWidth });
    });


</script>

WebApplication2/Areas/admin/Views/Events/Index.cshtml
@model IEnumerable<RS.DataModel.EventModel>
@using GridMvc.Html
@using RS.DataModel;

@{
    ViewBag.Title = ".:: Events ::..";
    Layout = "~/Areas/admin/Views/Shared/_Layout.cshtml";
}

<h1 style="color:#146eb0;text-align:left">कार्यक्रम</h1>
<hr />
<ol class="breadcrumb">
    <li><a href="#">प्रारम्भ</a></li>
    <li class="active">कार्यक्रम </li>
</ol>
<p style="text-align:left">
    <b> क्षत्रिय राठौर समाज के एडमिन पोर्टल मे आप का बहुत बहुत स्वागत है.</b> <br /><br />
</p>

<div class="col-lg-12 col-sm-12 col-md-12 text-right">
    @Html.ActionLink("नया कार्यक्रम", "AddEvent", "Events", new { @class = "btn btn-primary" })
    @*<button type="button" class="btn btn-danger"></button>*@
</div>


<div class="row">
    <div class="col-md-12">
        @if (TempData["Message"] != null)
            {
            <div class="alert alert-success" role="alert">@TempData["Message"]</div>
        }
    </div>
</div>

<br />

<div class="row">
    <div class="col-md-12">
        @Html.Grid(Model).Columns(columns =>
   {
       columns.Add()
             .Titled("")
             .SetWidth(10)
             .Filterable(true)
             .Sanitized(false)
             .Encoded(false)
             .RenderValueAs(c => Html.ActionLink(" ", "EditEvent", "Events", new { id = c.EventId }, new { @class = "glyphicon glyphicon-edit" })
             .ToHtmlString());

       if (Session["LoginSuccesFull"] != null && (((LoginModel)Session["LoginSuccesFull"]).Role == 99 || ((LoginModel)Session["LoginSuccesFull"]).Role == 1))
       {
           columns.Add()
               .Titled("")
               .SetWidth(10)
               .Filterable(true)
               .Sanitized(false)
               .Encoded(false)
               .RenderValueAs(c => Html.ActionLink(" ", "DeleteEvent", "Events", new { id = c.EventId }, new { onclick = "return confirm('Are you sure you wish to delete this Rathore details?');", @class = "glyphicon glyphicon-trash" })
               .ToHtmlString());
       }
       columns.Add(c => c.EventTypeName).Titled("कार्यक्रम प्रकार ");
       columns.Add(c => c.Subject).Titled("विषय").Filterable(true);
       columns.Add(c => c.EventDateFrom).Titled("दिनांक से  ").Filterable(true).Sortable(true)
               .RenderValueAs(c => Convert.ToDateTime(c.EventDateFrom).ToString("d"));
       columns.Add(c => c.EventTimeFrom).Titled("समय  से ").Filterable(true);
       columns.Add(c => c.EventDateTo).Titled("दिनांक तक ").Filterable(true).Filterable(true).Sortable(true)
               .RenderValueAs(c => Convert.ToDateTime(c.EventDateTo).ToString("d"));
       columns.Add(c => c.EventTimeTo).Titled("समय  तक ").Filterable(true);
       columns.Add(c => c.LocationName).Titled("स्थान ").Filterable(true);
       columns.Add(c => c.DistrictName).Titled("जिला").Filterable(true);
       columns.Add(c => c.CreatedByName).Titled("अंकित करने वाला ").Filterable(true);


   }).WithPaging(10).Sortable(true)


    </div>

</div>