WebApplication2/Areas/admin/Controllers/EventsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using RS.DataModel;
using RS.BusinessLogicLayer;

namespace WebApplication2.Areas.admin.Controllers
{
    [RathoreSamajAuth]
    public class EventsController : BaseController
    {
        EventBL _eventDetailBL;
        public EventsController()
        {
            _eventDetailBL = new EventBL();
        }
        // GET: admin/Events
        [RathoreSamajAuth(Order = 1, Roles = "1,2,99", Users = null)]
        public ActionResult Index()
        {
            List<EventModel> lstEventDetails = _eventDetailBL.GetAllEvent();
            return View(lstEventDetails);
        }

        [RathoreSamajAuth(Order = 1, Roles = "1,2,99", Users = null)]
        public ActionResult AddEvent()
        {
            @ViewBag.Style = "alert alert-success";
            //RathoreDetailModel rathoreDetails = new RathoreDetailModel();
            // BindDropdown(ref rathoreDetails);
            return View();
        }


        [HttpPost]
        [RathoreSamajAuth(Order = 1, Roles = "1,2,99", Users = null)]
        public ActionResult AddEvent(EventModel obj)
        {
            @ViewBag.Style = "alert alert-success";
            if (ModelState.IsValid)
            {

                obj.CreatedBy = LoginUserID;
                obj.EventDateFrom = Convert.ToDateTime(obj.EventDateFromFormated);
                obj.EventDateTo = Convert.ToDateTime(obj.EventDateToFormated);

                int result = _eventDetailBL.InsertEvent(obj);
                // BindDropdown(ref obj);
                ViewBag.Saved = true;

                if (result == 1)
                {
                    ViewBag.Style = "alert alert-success";
                    ViewBag.Message = "जानकारी डेटाबेस मे दर्ज हो गया है | धन्यवाद् ";
                    ModelState.Clear();
                }
                else
                {
                    ViewBag.Style = "alert alert-danger";
                    ViewBag.Message = "तकनिकी खराबी की वजह से आपका सन्देश नहीं मिला , कृपया दुबारा भेजे.  ";
                }
            }
            return View(obj);
        }


        [RathoreSamajAuth(Order = 1, Roles = "1,2,99", Users = null)]
        public ActionResult EditEvent(int id)
        {
            ViewBag.Style = "alert alert-success";
            EventModel eventModel = new EventModel();
            eventModel = _eventDetailBL.GetEventId(id);


            string datetimeFrom = string.Format("{0:yyyy-MM-dd}", eventModel.EventDateFrom);
            string datetimeTo = string.Format("{0:yyyy-MM-dd}", eventModel.EventDateTo);

            eventModel.EventDateFromFormated = datetimeFrom;
            eventModel.EventDateToFormated = datetimeTo;

            return View(eventModel);
        }


        [HttpPost]
        [RathoreSamajAuth(Order = 1, Roles = "1,2,99", Users = null)]
        public ActionResult EditEvent(EventModel obj)
        {
            @ViewBag.Style = "alert alert-success";
            if (ModelState.IsValid)
            {
                obj.ModifiedBy = LoginUserID;
                obj.EventDateFrom = Convert.ToDateTime(obj.EventDateFromFormated);
                obj.EventDateTo = Convert.ToDateTime(obj.EventDateToFormated);

                //string Name = Convert.ToString(TempData["Name"]).Trim();
                //DateTime DateofBirth = Convert.ToDateTime(TempData["DateofBirth"]);

                //TempData.Keep("Name");
                //TempData.Keep("DateofBirth");


                int result = _eventDetailBL.UpdateEvent(obj);

                ViewBag.Saved = true;

                if (result == 1)
                {
                    ViewBag.Style = "alert alert-success";
                    ViewBag.Message = "जानकारी डेटाबेस मे दर्ज हो गया है | धन्यवाद् ";
                }
                else
                {
                    ViewBag.Style = "alert alert-danger";
                    ViewBag.Message = "तकनिकी खराबी की वजह से आपका सन्देश नहीं मिला , कृपया दुबारा भेजे.  ";
                }

            }
            return View(obj);
        }


        [RathoreSamajAuth(Order = 1, Roles = "1,99", Users = null)]
        public ActionResult DeleteEvent(int id)
        {
            int result = _eventDetailBL.DeleteEvent(id);
            if (result == 1)
            {
                TempData["Message"] = "चयन किया रिकॉर्ड मिटा दिया गया है !! ";
            }
            else
            {
                TempData["Message"] = "तकनिकी खराबी की वजह से आपका सन्देश नहीं मिला , कृपया दुबारा भेजे.  ";
            }

            return RedirectToAction("Index");
        }


        [HttpPost]
        public JsonResult DistrictAutosuggest(string Prefix)
        {
            AutoSuggestTextBL obj = new AutoSuggestTextBL();

            var distList = (from N in obj.GetAllDistrict()
                            where N.Value.ToUpper().StartsWith(Prefix.ToUpper())
                            select new { N.Value });
            return Json(distList, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult LocationAutosuggest(string Prefix)
        {
            AutoSuggestTextBL obj = new AutoSuggestTextBL();

            var distlocation = (from N in obj.GetAllLocation()
                                where N.Value.ToUpper().StartsWith(Prefix.ToUpper())
                                select new { N.Value });
            return Json(distlocation, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult EventAutosuggest(string Prefix)
        {
            AutoSuggestTextBL obj = new AutoSuggestTextBL();

            var eventsType = (from N in obj.GetEventType()
                                where N.Value.ToUpper().StartsWith(Prefix.ToUpper())
                                select new { N.Value });
            return Json(eventsType, JsonRequestBehavior.AllowGet);
        }
    }
}

WebApplication2/Controllers/EventController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using RS.DataModel;
using RS.BusinessLogicLayer;

namespace WebApplication2.Controllers
{
    public class EventController : Controller
    {

        EventBL _eventDetailBL;
        public EventController()
        {
            _eventDetailBL = new EventBL();
        }
        // GET: Event
        public ActionResult Index()
        {
            EventModelDetails lstEventDetails = new EventModelDetails();

            var allEvents = _eventDetailBL.GetAllEvent();

            lstEventDetails.CurrentMonthEvent = allEvents.Where(o => o.EventDateFrom.Value.Month == DateTime.Now.Month).ToList();
            lstEventDetails.TotalEvent = allEvents;
            return View(lstEventDetails);
        }

        public ActionResult EventDetails(int id)
        {
            ViewBag.Style = "alert alert-success";
            EventModelView eventModelView = new EventModelView();
            eventModelView.SelectedEvent = _eventDetailBL.GetEventId(id);
            eventModelView.CurrentMonthEvent = _eventDetailBL.GetAllEvent().Where(o => o.EventDateFrom.Value.Month == DateTime.Now.Month).ToList();

            return View(eventModelView);
        }
    }
}

WebApplication2/Views/Event/EventDetails.cshtml
@model RS.DataModel.EventModelView
@{
    ViewBag.Title = "EventDetails";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="row">
    <div class="col-md-12">
        @Html.ActionLink("पीछे जाये", "Index", "Event", new { @class = "btn btn-danger" }) &nbsp;
        <br />
        <br />
        <div class="panel panel-Events-Main">
            <div class="panel-heading" role="tab" id="headingOne">
                <h4 class="panel-title">
                    <i class="fa fa-calendar" style="color:#000" aria-hidden="true"></i>&nbsp;<b>@Model.SelectedEvent.Subject.Trim()</b>
                    <b> @(string.Format("{0:dd-MM-yyyy}", Model.SelectedEvent.EventDateFrom)  ) </b> @(Model.SelectedEvent.EventDateFrom >= DateTime.Now ? "मे होने वाला है" : "को हुआ है " )
                </h4>
            </div>
            <div class="panel-collapse collapse in" role="tabpanel" aria-labelledby="headingOne">
                <div class="panel-body">
                    <div class="col-md-12">
                        <b style="color:#0d4398">कार्यक्रम  प्रकार  : </b> <span style="color:#000000;font-size: 15px;font-weight:bold"> @Model.SelectedEvent.EventTypeName </span>
</div>
                    <div class="col-md-12">
                        <b style="color:#0d4398">स्थान   : </b>  <span style="color:#ff6a00;font-size: 15px;font-weight:bold">   @Model.SelectedEvent.LocationName, @Model.SelectedEvent.DistrictName </span>
                    </div>
                    <div class="col-md-12">
                        <b style="color:#0d4398">समय    : </b>  <span style="color:#000000;font-size: 15px;font-weight:bold">   @(string.Format("{0:dd-MM-yyyy}", Model.SelectedEvent.EventDateFrom)  )   @Model.SelectedEvent.EventTimeFrom से @(string.Format("{0:dd-MM-yyyy}", Model.SelectedEvent.EventDateTo))  @Model.SelectedEvent.EventTimeTo </span>
</div>
                    <hr />
                    <div class="col-md-12">
                         @Html.Raw(Model.SelectedEvent.Body)
                    </div>
                    <div class="col-md-12 text-right">
                        <hr />
                        <b style="color:#13836f"> ~  @(Model.SelectedEvent.CreatedBy == 0 ? "Admin" : Model.SelectedEvent.CreatedByName)</b>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-12 text-left">
        @Html.ActionLink("पीछे जाये", "Index", "Event", new { @class = "btn btn-danger" }) &nbsp;
        <a href="whatsapp://send" data-text="@(Model.SelectedEvent.Subject + " on " + string.Format("{0:dd-MM-yyyy}", @Model.SelectedEvent.EventDateFrom))" class="wa_btn wa_btn_s" data-href="http://rathoresamaj.clinikage.com/Event/EventDetails/@Model.SelectedEvent.EventId"
           onClick="ga('send', 'event', { eventCategory: 'Social', eventAction: 'Share', eventLabel: 'WhatsAppShare', eventValue: 0});">
            <button class="btn btn-success"><i class="fa fa-whatsapp" aria-hidden="true"></i></button>

            <div class="fb-like"  data-href="http://rathoresamaj.clinikage.com/Event/EventDetails/@Model.SelectedEvent.EventId" data-layout="button_count"
                 data-action="like" data-size="large" data-show-faces="true" data-share="true"></div>

        </a>
    </div>
</div>
<br />
<div class="row">
    <div class="col-md-12 subheaderText" style="text-align:left">
        <u> तत्कालीन महीने के कार्यक्रम </u>
    </div>
    </div>
<br />
    <div class="row">
        <div class="col-md-12">

            @if (Model.CurrentMonthEvent.Count() > 0)
            {
                foreach (var item in Model.CurrentMonthEvent)
                {
                    <div class="panel panel-Events-Main">
                        <div class="panel-heading" role="tab" id="headingOne">
                            <h4 class="panel-title">
                                <a role="button" data-toggle="collapse" style="text-decoration:none" data-parent="#accordion" href="#@(item.EventId + "_" + 1)" 
                                   aria-expanded="true" aria-controls="collapseOne">
                                    <i class="fa fa-calendar" style="color:#000" aria-hidden="true"></i>&nbsp;<b>
                                        @Html.ActionLink(item.Subject.Trim(), "EventDetails", "Event", new { id = item.EventId })
                                    </b>
                                </a> on <b> @(string.Format("{0:dd-MM-yyyy}", item.EventDateFrom)  )</b>
                            </h4>
                        </div>
                    </div>
                }
            }
            else
            {
                <div class="panel-body">
                    <div class="col-md-12 text-center">
                        <div class="alert alert-active" role="alert">
                            <b style="font-size:14px">  इस महीने के कोई भी कार्यक्रम दर्ज नहीं है. </b>
                        </div>
                    </div>
                </div>
            }

        </div>

    </div>

    <br /><br />


    <div id="fb-root"></div>
    <script>
        (function (d, s, id) {
            var js, fjs = d.getElementsByTagName(s)[0];
            if (d.getElementById(id)) return;
            js = d.createElement(s); js.id = id;
            js.src = 'https://connect.facebook.net/en_GB/sdk.js#xfbml=1&version=v2.11';
            fjs.parentNode.insertBefore(js, fjs);
        }(document, 'script', 'facebook-jssdk'));</script>

WebApplication2/Views/Event/Index.cshtml
@model RS.DataModel.EventModelDetails
@using GridMvc.Html
@using RS.DataModel;

@{
    ViewBag.Title = "Events in Rathore Samaj";
}

<div class="row">
    <div class="col-md-12 subheaderText" style="text-align:left">
        <u> तत्कालीन महीने के कार्यक्रम </u>
    </div>
    <br />
    <div class="row">
        <div class="col-md-12">
            @foreach (var item in Model.CurrentMonthEvent)
            {
                <div class="panel panel-Events-Main">
                    <div class="panel-heading" role="tab" id="headingOne">
                        <h4 class="panel-title">
                            <a role="button" data-toggle="collapse" style="text-decoration:none" data-parent="#accordion" href="#@(item.EventId + "_" + 1)" aria-expanded="true" aria-controls="collapseOne">
                                <i class="fa fa-arrow-circle-right" style="color:#000" aria-hidden="true"></i>&nbsp;<b>@item.Subject.Trim()</b>
                            </a> on <b> @(string.Format("{0:dd-MM-yyyy}", item.EventDateFrom)  )</b>
                        </h4>
                    </div>
                    <div id="@(item.EventId + "_" + 1)" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="headingOne">
                        <div class="panel-body">
                            <div class="col-md-12">
                                <b style="color:#0d4398">कार्यक्रम  प्रकार  : </b>  @item.EventTypeName
                            </div>
                            <div class="col-md-12">
                                <b style="color:#0d4398">स्थान   : </b>  <span style="color:#ff6a00;font-size: 15px">   @item.LocationName, @item.DistrictName </span>
                            </div>
                            <div class="col-md-12">
                                <b style="color:#0d4398">समय    : </b>   @(string.Format("{0:dd-MM-yyyy}", item.EventDateFrom)  )   @item.EventTimeFrom से @(string.Format("{0:dd-MM-yyyy}", item.EventDateTo))  @item.EventTimeTo
                            </div>
                            <div class="col-md-12">
                                <b style="color:#0d4398">विषय   : </b> @Html.Raw(item.Body.Length > 2000 ? item.Body.Substring(0, 1990) : item.Body) ...
                            </div>
                            <div class="col-md-12">
                                <br />
                                <br />
                                @Html.ActionLink("विस्तार से देखे", "EventDetails", "Event", new { id = item.EventId }, new { @class = "btn btn-danger" })
                            </div>
                            @*<div class="col-md-12 text-right">
                                <b style="color:#13836f"> ~  @(item.CreatedBy == 0 ? "Admin" : @item.CreatedByName)</b>
                            </div>*@
                        </div>
                    </div>
                </div>
            }

        </div>

    </div>
</div>


<div class="row">
    <div class="col-md-12 subheaderText" style="text-align:left">
        <u> समस्त कार्यक्रम  </u>
    </div>
    <div class="row">
        <div class="col-md-12">
            @foreach (var item in Model.TotalEvent)
            {
                <div class="panel panel-Events">
                    <div class="panel-heading" role="tab" id="headingOne">
                        <h4 class="panel-title">
                            <a role="button" data-toggle="collapse" style="text-decoration:none" data-parent="#accordion" href="#@item.EventId" aria-expanded="true" aria-controls="collapseOne">
                                <i class="fa fa-arrow-circle-right" style="color:#000" aria-hidden="true"></i>&nbsp;<b>@item.Subject.Trim()</b>
                            </a> मे  <b> @(string.Format("{0:dd-MM-yyyy}", item.EventDateFrom)  )</b>
                        </h4>
                    </div>
                    <div id="@item.EventId" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingOne">
                        <div class="panel-body">
                            <div class="col-md-12">
                                <b style="color:#0d4398">कार्यक्रम  प्रकार  : </b>  @item.EventTypeName
                            </div>
                            <div class="col-md-12">
                                <b style="color:#0d4398">स्थान   : </b>  <span style="color:#ff6a00;font-size: 15px">   @item.LocationName, @item.DistrictName </span>
                            </div>
                            <div class="col-md-12">
                                <b style="color:#0d4398">समय    : </b>   @(string.Format("{0:dd-MM-yyyy}", item.EventDateFrom)  )   @item.EventTimeFrom से @(string.Format("{0:dd-MM-yyyy}", item.EventDateTo))  @item.EventTimeTo
                            </div>
                            <div class="col-md-12">
                                <b style="color:#0d4398">विषय   : </b> @Html.Raw(item.Body.Length > 2000 ? item.Body.Substring(0, 1990) : item.Body) ...
                                <br /><br />
                            </div>
                            <div class="col-md-12">
                                <br /><br />
                                @Html.ActionLink("विस्तार से देखे", "EventDetails", "Event", new { id = item.EventId }, new { @class = "btn btn-danger" })
                            </div>
                            @*<div class="col-md-12 text-right">
                                <b style="color:#13836f"> ~  @(item.CreatedBy == 0 ? "Admin" : @item.CreatedByName)</b>
                            </div>*@
                        </div>
                    </div>
                </div>
            }

            @*@Html.Grid(Model).Columns(columns =>
                {
                    columns.Add(c => c.EventTypeName).RenderValueAs(o => "<table><tr><td>" + o.EventTypeName + "</td></tr><tr><td>" + o.LocationName + "</ td ></ tr ></table>").Titled(" ").Encoded(true);
                    //columns.Add(c => c.EventTypeName).Titled("कार्यक्रम प्रकार ");
                    //columns.Add(c => c.Subject).Titled("विषय").Filterable(true);
                    //columns.Add(c => c.EventDateFrom).Titled("दिनांक से  ").Filterable(true).Sortable(true)
                    //        .RenderValueAs(c => Convert.ToDateTime(c.EventDateFrom).ToString("d"));
                    //columns.Add(c => c.EventTimeFrom).Titled("समय  से ").Filterable(true);
                    //columns.Add(c => c.EventDateTo).Titled("दिनांक तक ").Filterable(true).Filterable(true).Sortable(true)
                    //        .RenderValueAs(c => Convert.ToDateTime(c.EventDateTo).ToString("d"));
                    //columns.Add(c => c.EventTimeTo).Titled("समय  तक ").Filterable(true);
                    //columns.Add(c => c.LocationName).Titled("स्थान ").Filterable(true);
                    //columns.Add(c => c.DistrictName).Titled("जिला").Filterable(true);
                    //columns.Add(c => c.CreatedByName).Titled("अंकित करने वाला ").Filterable(true);


                }).WithPaging(10).Sortable(true).Named("FullEventDetails")*@


        </div>

    </div>
</div>

<script type="text/javascript">
    $(document).ready(function () {
        $('.collapse').on('shown.bs.collapse', function () {
            $(this).parent().find(".fa-arrow-circle-right").removeClass("fa-arrow-circle-right").addClass("fa-arrow-circle-down");
        }).on('hidden.bs.collapse', function () {
            $(this).parent().find(".fa-arrow-circle-down").removeClass("fa-arrow-circle-down").addClass("fa-arrow-circle-right");
        });
    });
</script>