WebApplication2/Areas/admin/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using RS.DataModel;
using RS.BusinessLogicLayer;

namespace WebApplication2.Areas.admin.Controllers
{
    public class LoginController : Controller
    {
        // GET: admin/Login
        public ActionResult Index()
        {
            Session["LoginSuccesFull"] = null;
            @ViewBag.Message = string.Empty;
            return View();
        }

        
        [HttpPost]
        public ActionResult Index(LoginModel obj)
        {
            Session["LoginSuccesFull"] = null;
            if (ModelState.IsValid)
            {
                if (obj.UserName == "admin" && obj.Password == "admin123")
                {
                    LoginModel _login = new LoginModel();
                    _login.Name = "Admin";
                    _login.RathoreDetailId = 0;
                    _login.Role = 99;
                    Session["LoginSuccesFull"] = _login;

                    return RedirectToAction("Index", "Home", new { area = "Admin" });
                }
                else
                {
                    LoginBL _loginBL = new LoginBL();
                    //Session["LoginSuccesFull"] = null;

                    LoginModel result = _loginBL.CheckLoginDetail(obj);
                    ViewBag.Saved = true;

                    if (result != null && result.Name != string.Empty)
                    {
                        _loginBL.UpdateLoginInfoDetail(result);
                        Session["LoginSuccesFull"] = result;
                        return RedirectToAction("Index", "Home", new { area = "Admin" });
                    }
                    else
                    {
                        @ViewBag.Message = "Please provide valid username and password.";
                        return View(obj);
                    }
                   
                }

                //LoginBL _loginBL = new LoginBL();
                //Session["LoginSuccesFull"] = null;

                //LoginModel result = _loginBL.CheckLoginDetail(obj);
                //ViewBag.Saved = true;

                //if (result != null && result.Name != string.Empty)
                //{
                //    _loginBL.UpdateLoginInfoDetail(result);
                //    Session["LoginSuccesFull"] = result;
                //    return RedirectToAction("Index", "Home", new { area = "Admin" });
                //}
                //else
                //{
                    
                //    @ViewBag.Message = "तकनिकी खराबी की वजह से आपका सन्देश नहीं मिला , कृपया दुबारा भेजे.  ";
                //}

            }
            return View(obj);
        }
    }


}

WebApplication2/Controllers/ContactsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using RS.DataModel;
using RS.BusinessLogicLayer;

namespace WebApplication2.Controllers
{
    public class ContactsController : Controller
    {
        // GET: Contacts
        public ActionResult Index()
        {
            ViewBag.Saved = false;
            @ViewBag.Message = "";
            return View();
        }


        [HttpPost]
        public ActionResult Index(ContactModel obj)
        {

            if(ModelState.IsValid)
            {
                ContactDetailBL _contactDetailBL = new ContactDetailBL();
                obj.IpAddress = "Host Name - " +  Request.UserHostName + ": IP Address -" + Request.UserHostAddress;
                obj.IpAddress = Request.UserHostName;
                //string url = String.Format("http://iplocationtools.com/ip_query2.php?ip={0}", Request.UserHostAddress);
                //XDocument xDoc = XDocument.Load(url);
                int result = _contactDetailBL.InsertContact(obj);
                ViewBag.Saved = true;

                if (result == 1)
                {
                    @ViewBag.Message = "आपका सन्देश हमें मिल गया है, धन्यवाद् ";
                    ModelState.Clear();
                    return View();
                }
                else
                {
                    @ViewBag.Message = "तकनिकी खराबी की वजह से आपका सन्देश नहीं मिला , कृपया दुबारा भेजे.  ";
                }

            }
            return View(obj);
        }
    }
}

WebApplication2/Controllers/GallaryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebApplication2.Controllers
{
    public class GallaryController : Controller
    {
        // GET: Gallary
        public ActionResult Index()
        {
            return View();
        }
    }
}

WebApplication2/Controllers/NewsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebApplication2.Controllers
{
    public class NewsController : Controller
    {
        // GET: News
        public ActionResult Index()
        {
            return View();
        }
    }
}

WebApplication2/Areas/admin/Views/Shared/_Layout.cshtml
@using RS.DataModel;

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - राठौर समाज की जानकारी </title>

    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/admin.css" rel="stylesheet" />
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.js"></script>
    <link href="~/Content/admin.css" rel="stylesheet" />
    <link href="@Url.Content("~/Content/Gridmvc.css")" rel="stylesheet" />
    <link href="@Url.Content("~/Content/bootstrap.min.css")" rel="stylesheet" />
    <script src="@Url.Content("~/Scripts/gridmvc.min.js")"></script>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")

</head>
<body>
    <div class="navbar navbar-inverse" style="border-bottom: 5px solid rgba(65, 226, 204, 0.6196078431372549)">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("राठौर समाज - एडमिन पोर्टल ", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse" style="float:right !important">

                <ul class="nav navbar-nav">

                    <li>  @Html.ActionLink("प्रारम्भ ", "Index", "Home")</li>

                    @if (Session["LoginSuccesFull"] != null && ((LoginModel)Session["LoginSuccesFull"]).Role != null && (((LoginModel)Session["LoginSuccesFull"]).Role == 1 || ((LoginModel)Session["LoginSuccesFull"]).Role == 2 ||
                                             ((LoginModel)Session["LoginSuccesFull"]).Role == 3 || ((LoginModel)Session["LoginSuccesFull"]).Role == 99))
                    {
                        <li>@Html.ActionLink("राठौर जानकारी", "Index", "RathoreDetails")</li>
                    }

                    @if (Session["LoginSuccesFull"] != null && ((LoginModel)Session["LoginSuccesFull"]).Role != null && (((LoginModel)Session["LoginSuccesFull"]).Role == 1 || ((LoginModel)Session["LoginSuccesFull"]).Role == 2 ||
                                                     ((LoginModel)Session["LoginSuccesFull"]).Role == 3 || ((LoginModel)Session["LoginSuccesFull"]).Role == 99))
                    {
                        <li>@Html.ActionLink("कार्यक्रम", "Index", "Events")</li>
                    }
                    @if (Session["LoginSuccesFull"] != null && ((LoginModel)Session["LoginSuccesFull"]).Role != null && (((LoginModel)Session["LoginSuccesFull"]).Role == 1 || ((LoginModel)Session["LoginSuccesFull"]).Role == 2 ||
                                                     ((LoginModel)Session["LoginSuccesFull"]).Role == 3 || ((LoginModel)Session["LoginSuccesFull"]).Role == 99))
                    {
                        <li>@Html.ActionLink("समाचार", "Index", "News")</li>
                    }
                    @*@if (Session["LoginSuccesFull"] != null && ((LoginModel)Session["LoginSuccesFull"]).Role != null && (((LoginModel)Session["LoginSuccesFull"]).Role == 1 || ((LoginModel)Session["LoginSuccesFull"]).Role == 2 ||
                                                                         ((LoginModel)Session["LoginSuccesFull"]).Role == 3 || ((LoginModel)Session["LoginSuccesFull"]).Role == 99))
                    {
                        <li>@Html.ActionLink("एल्बम", "Index", "Albums")</li>

                        <li>@Html.ActionLink("चित्र", "Index", "Gallary")</li>
                    }*@

                    @if (Session["LoginSuccesFull"] != null && ((LoginModel)Session["LoginSuccesFull"]).Role != null && (((LoginModel)Session["LoginSuccesFull"]).Role == 1 || ((LoginModel)Session["LoginSuccesFull"]).Role == 99))
                    {
                        <li>@Html.ActionLink("संपर्क ", "Index", "Contacts")</li>
                    }
                    <li> @Html.ActionLink("बहार निकले", "Index", "Login", new { Area = "Admin" }, new { @id = "Logout" } )  @*@Html.ActionLink("बहार निकले", "Index", "Login", new {  @id="Logout"})*@</li>
                   

                </ul>


                    
                </div>
            </div>
        </div>
        <div class="container body-content">
            @RenderBody()
        </div>
        <footer class="col-lg-12">
            <hr />
            <p style="margin-left:20px;">  &copy; Rathore  Samaj - @DateTime.Now.Year - <span style="color:orangered"> Designed and Code by <b> Passion software</b></span></p>
        </footer>

        @RenderSection("scripts", required: false)
    </body>
</html>
<style>

    #Logout {
        color: red !important;
    }
</style>